#!/bin/bash
docker run --rm -it --network=host --ipc=host --shm-size=16G --ulimit memlock=-1 --ulimit stack=67108864 --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=all --workdir /app -v "$(pwd)":/app $USER/skipformer
